version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r my-api/requirements.txt
  build:
    commands:
      - python -m unittest discover -s my-api
artifacts:
  files:
    - '**/*'
  base-directory: my-api